name: Running Tests

on: [push]

jobs:
  build_and_test_linux:
    name: "Rust Lisp"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test